Added the daily load formula
ankitects/anki-manual pull request #318
Opened 2024-12-04 22:37 UTC by Expertium

https://www.reddit.com/r/Anki/comments/1h6n9dk/comment/m0fza4c/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Originally I wanted to add the formula, but sorata told me not to. Seeing that at least once more person wants to see it, I think we should add it.

2024-12-05 08:02 UTC, brishtibheja commented
It's a sample of a few selected person wanting this, but if it's to be done, I think we can make it cleaner using mathjax.

In `book.toml`, have `mathjax-support = true` to enable mathjax.

https://github.com/ankitects/anki-manual/blob/bb51e749f4f33ac8395693ae964e5ee9d088b97a/book.toml#L16-L20

Then format the equation using mathjax syntax. Using `\\[`, `\\]` as delimiters, you'd write:

```
\[\frac{1}{I_1} + \frac{1}{I_2} + \frac{1}{I_3} + \dots + \frac{1}{I_n}\]
```

This renders as: 

$$\frac{1}{I_1} + \frac{1}{I_2} + \frac{1}{I_3} + \dots + \frac{1}{I_n}$$
___

Ref: https://rust-lang.github.io/mdBook/format/mathjax.html

2024-12-05 08:12 UTC, Expertium commented
I don't know how to do that. Feel free to PR.

2024-12-05 09:34 UTC, brishtibheja requested changes

2024-12-05 09:34 UTC, brishtibheja commented on src/stats.md
> +$$\frac{1}{I_1} + \frac{1}{I_2} + \frac{1}{I_3} + \dots + \frac{1}{I_n}$$
```suggestion
\\[\frac{1}{I_1} + \frac{1}{I_2} + \frac{1}{I_3} + \dots + \frac{1}{I_n}\\]
```

2024-12-05 09:34 UTC, brishtibheja commented on src/stats.md
> +where In is the interval of
```suggestion

Here, \\(I_n\\) is the interval of
```

2024-12-05 09:34 UTC, brishtibheja commented on src/stats.md
> +Example: you have a card with an interval of 10 days and a card with an interval of 50 days.
how about a newline here.
```suggestion

Example: you have a card with an interval of 10 days and a card with an interval of 50 days. 
```

2024-12-05 09:34 UTC, brishtibheja commented on src/stats.md
> +Daily load = \\( ]frac{1}{10} + \frac{1}{50} = 0.12 \\), meaning that, *on average*, you will have 0.12 due cards per day.
```suggestion
Daily load = \\(\frac{1}{10} + \frac{1}{50} = 0.12\\), meaning that, _on average_, you will have 0.12 due cards per day.
```

2024-12-16 16:35 UTC, Expertium commented
@dae

2024-12-23 12:06 UTC, dae commented
Thank you both, and sorry about the delay.

2024-12-23 12:06 UTC, merged